name: mirror github ibm

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  mirror:
    uses: ibm-skills-network/.github/.github/workflows/mirror-github-ibm.yml@main
    with:
      repo_name: tahoe-lti
    secrets:
      ssh_private_key:
          ${{ secrets.MIRROR_GITHUB_IBM_SSH_PRIVATE_KEY }}
